### ISSUE TITLE
Version 2.1.8 breaks self-hosted macOS ARM Github Actions runner

### ISSUE THREAD

**Issue by cknitt** [ocaml/setup-ocaml#735] opened 2023-12-07 08:15 UTC
We have a self-hosted macOS ARM Github Actions runner for the [ReScript](https://rescript-lang.org) CI.

Since setup-ocaml 2.1.8, we are getting the following error in CI on that runner (see e.g. https://github.com/rescript-lang/rescript-compiler/actions/runs/7117236442/job/19378552445):

```
Run ocaml/setup-ocaml@v2
Retrieve the opam cache
Install opam
Initialise the opam state
Error: Unable to locate executable file: brew. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

This is probably due to this change? https://github.com/ocaml/setup-ocaml/commit/2d84a0fc9b5dec7d80e65bf621d1497c946b0bab

**Comment by smorimoto** [comment] 2023-12-07 11:55
Yeah, that's definitely the cause.
Actually, this action doesn't officially support self-hosted runners yet.
I think the short term workaround is to expose the environment variable.

**Comment by cknitt** [comment] 2023-12-08 08:24
> I think the short term workaround is to expose the environment variable.

What exactly do you mean? Expose the environment variable where/how?

**Comment by smorimoto** [comment] 2023-12-09 14:41
Just set `GITHUB_ACTIONS` to true on the runner.

**Comment by cknitt** [comment] 2023-12-12 14:12
I tried:

1. Starting the self-hosted runner with `GITHUB_ACTIONS=true ./run.sh`. This did not have any effect.
1. Setting the variable in the Github actions admin UI. This is not allowed, see screenshot.

Am I missing something?

<img width="717" alt="Bildschirmfoto 2023-12-12 um 15 09 09" src="https://github.com/ocaml/setup-ocaml/assets/591384/262b1d5b-5d4f-4fd0-bea8-d9b4f5bc09f3">

**Comment by smorimoto** [comment] 2023-12-12 14:54
It's pretty weird that 1 doesn't work. How about explicitly exporting the environment variable globally?

**Comment by smorimoto** [comment] 2024-06-13 06:25
On second thought, it feels like brew is kind of a requirement so close this.

**Closed** 2024-06-13 06:24 UTC
